### ISSUE TITLE
Setup from scratch

### ISSUE THREAD

**Issue by MichaelLangbein** [gfzriesgos/shakyground#8]
Hi guys!
Just tested if shakyground works on my windows machine after a git-clone.
Noticed two items:

 - File `USGSSlopeBasedTopologyProxy.grd` isn't present, but can be easily downloaded from [here](https://earthquake.usgs.gov/data/vs30/). <= I could add a tiny script to download that file
 - `database.hdf5` isn't present. Shoud we just open hfd5 with `mode="a"` [here](https://github.com/gfzriesgos/shakyground/blob/0067f56ada96d5bbbe67333804c94e99c94ba052/shakemap_lite.py#L290)?

Will gladly create a PR if you want!
Cheers

**Comment by nbrinckm** [comment]
I'm honestly not sure about the usage on Windows (we are all Linux Fanboys...).

Basically we use a dockerfile that already contain the grids that we need to use. We build it in that repo here: https://github.com/gfzriesgos/shakyground-grid-file

The grid itself is too large to be easily included in our repo here, so we had to find a workaround - and as we don't touch the grid itself that often we decided to externalize it into its own dockerfile, so that we don't have to download the grid over and over again when we make a change on the code of shakyground itself.

So if you have docker inplace, you could reuse the `gfzriesgos/shakyground-grid-file:20211011` image that includes all the grid files. (Otherwise you could follow the steps here: https://github.com/gfzriesgos/shakyground-grid-file/blob/master/Dockerfile#L26 to build the grids youself).


Regarding to the `database.hdf5` file: I'm not completely into the shakyground code (we got the code from Graeme, who himself wrote a shakyground2 version in the last year), so please forgive me if I'm not sure about the details here.
From my understanding the script creates this file & fills it with the necessary structures. It should be purely temporary. (And I would even say using the append-mode would be wrong, as the file could then contain data from older runs).

So the question on my side is: Does you get an error message for the hdf5 file? I'm honestly expecting it to work as it is, but if you get an error message on windows, we may have to dig a little bit deeper into the stuff.


(And in any case we should improve the docs - I guess - to support the users in setting the stuff up locally).

**Comment by nbrinckm** [comment]
As I see that again today, I think we can point to the buildall repo: https://github.com/riesgos/buildall

**Comment by MichaelLangbein** [comment]
Indeed!
Closing this issue, since this is being handled at  https://github.com/riesgos/buildall
